### ISSUE TITLE
RFID Access - Nottinghack 2.5 Plan

### ISSUE THREAD

**Issue by sid351** [NottingHack/rules#24]
There isn't really any mention of the RFID approach we'll be using in the 2.5 plan, and while that will happen before the end of the consultation period on the rules as a whole, there have been some conversations taking place that are perhaps better here.

So...copying the jist (key points from the Slack chat in #Networking today (2016-01-06 around 13:00ish)):

- The new doors downstairs will all have break-to-exit switches, and there will of course be a manual override for when things go wrong
- they will be swipe in and swipe out
- so you can't open the door if you have your card in the laser cutter / mill / lathe ......
- you shouldnt be leaving a tool unattended anyway
- what if someone's visitor wants to visit the toilet?
- if they are your guest you accompany them
- people will just prop open doors
- No, they wont, Because if they do, they will, I expect, suffer some sort of disciplinary action.
- can laser cuts be interrupted and resumed?
- Yes, but Your card still has to be on the machine for that to work though
- A change will be going into HMS to allow people to have more than one card
- So if you need to, you can leave your card on the laser cutter (with it paused, of course) and use your other card to get to the toilet
- Everyone with access to a RFID controlled tool will ​*need*​ a second card
- Everyone will also be migrated to white cards anyway in the near future
- so if a friend wants to go out for a pizza you have to "see" them to the door?
- if they want to wander around the space themselves, they need to come in on a Wednesday, get a tour and become a member
- That brings up an interesting question - who is responsible for visitors on a Wednesday night?
- They're often walking around unattended. If we don't want individual friends of members going to the loo, how do we justify having the general public all over the place?
- I think the general consensus was that we are a space are responsible for people on open nights, and I ​*suppose*​????? that means the responsible trustee is the eventual responsible person

**Comment by geeksareforlife** [comment]
I think we can take the RFID stuff out of this, but a discussion about visitors would probably be good

**Comment by sid351** [comment]
In Pull Request #25 I've taken the visitors elements from this and edited the guests and visitors rule as per my take on the conversation.

**Comment by jamesfowkes** [comment]
I think that expecting members to accompany guests everywhere is unrealistic. I'm not making a comment on how desirable it is, I just don't think people will do it.

To use Russell's example, people aren't (in general) going to escort a friend to the toilet (unless forced to by an RFID system).

I think a more realistic rule might specify areas in which visitors *must* be attended and areas where they can be left to roam free, making it clear that they are still your responsibility.

I tried amending the rule, but couldn't find the right wording.

**Comment by jamesfowkes** [comment]
I think the following might happen:
1. Guest goes unattended to kitchen to get cup of tea
2. Guest is challenged, resulting in member being disciplined.
3. Member thinks rule is stupid and says so publicly.
4. Everyone agrees that guests going to make a cup of tea shouldn't result in disciplinary actions and that the rule is stupid.

**Comment by geeksareforlife** [comment]
Or:

4. Guests are no longer allowed because members can't look after them and our insurance disappears

**Comment by geeksareforlife** [comment]
We have a simple issue - our insurance is issued on the understanding that guests are accompanied.

If that is no longer the case, we will need to go back to our insurers and ask for them to update the policy to include non-inducted people wandering about the space however they please.

I dread to think what our premiums would be for that

**Comment by jamesfowkes** [comment]
Does that make a specific exemption for open nights? And other times when there might be guests in?

**Comment by geeksareforlife** [comment]
Yes, we talked about the events we run, and we have specific coverage for those.

**Comment by sid351** [comment]
I suppose I don't know, but how often do we have visitors in the space anyway?  The barrier to membership isn't exactly high.

We actually do a lot more Open events that we perhaps think (acoustic night, IoThurs, Retro Computers) and more in the future (Saturdays & Exhib days), so that "barrier" would be coming down anyway.

**Comment by geeksareforlife** [comment]
I'm not suggesting that we stick to them like glue, but we are responsible for our visitors in the space.  If we take the example we were talking about this morning - if your visitor goes from the laser cutter in the new space to the toilets upstairs (assuming all work is complete) they have to go through two rfid doors, past the front entrance and up the stairs to the toilet (assuming able bodied visitor)

Can you guarantee that they won't hear the doorbell ring and let someone into the space?  Or get lost because your directions were a bit crap and walk right into the metalworking area?

If you are sat in the Kitchen, or the Studio and they need the toilet then it is easy - you point at the door and they go.  I'm not suggesting you escort them to the toilet, but that you accompany them upstairs and do something else, like make both of you a cup of tea or something

**Comment by geeksareforlife** [comment]
Also, all the "you" in there is generic, not a specific person

**Comment by jamesfowkes** [comment]
As I say, I don't disagree with the principle. I just think it'll be hard to monitor/maintain in practice. If we need the rule for insurance purposes though, I guess needs to stay.

**Comment by geeksareforlife** [comment]
:+1:

**Comment by jamesfowkes** [comment]
Yay for weird insurance things. How did that conversation go?
"Every week we have loads of completely new, unknown people wandering round our workshop full of expensive dangerous stuff."
"Yeah, we can insure that no probs mate."
"Also, we'd like member's guests to go to the loo without an escort"
"GET. OUT."

**Comment by sid351** [comment]
With more RFID doors it becomes easier to maintain (although issuing 2nd cards to everyone - unless they can be restricted to tools only or doors only).

It's also not that far removed from common sense.  I've had a go at rewording the rule to make it clear what the difference between a visitor or a guest is in #25.  Perhaps I've gone a bit too far with the accompanying them bit though.

As long as the rule isn't far from common sense and has a clear reason why (our insurance says so) then I think most people will get it.

**Comment by geeksareforlife** [comment]
Oh no - technically we are all "looking after" the new people during open nights.  And they are escorted around the space on "tours" where they get told not to touch the dangerous things.

And then it was a question about other visitors to the space, and are they escorted.  I said, "do you mean is someone responsible for them", they say "yes, and with them at all times", I say "yes"

**Comment by sid351** [comment]
I've updated the wording in #25 a bit more now.

**Comment by rlp10** [comment]
Unless the insurance policy itself specifies it, I don't think that we need to define what "accompany" means. It is afterall an ordinary English word, not legal or insurance jargon.

It's for members to take responsibility for their own guests by "accompanying" them, which depends on the circumstances. In my view, accompanying a child in the workshop would require a higher proximity than accompanying an adult who is fetching a glass of water from the kitchen, for example.

Before there is a final commit, I do think that it would be helpful for James H to confirm that the rule fully covers the requirement in the insurance policy. Since that is the obligation that we have made to the insurer, why not just mirror it with the same words (or very similar words) in the rules? That way we can be sure that we are correctly passing along the obligation to the members.

I'm not certain that it is desirable to actually say in the rule though that its reason is for insurance purposes. I'm in two minds over this and think it depends on the wording. We don't want it to sound like a "second class" rule, i.e. we only have it because the insurer makes us, not because we think that its important ourselves.

It's worth remembering that the interests of the insurer in this instance are 100% aligned with our own: we both want to reduce the risk of accidents and claims. When they tell us that a rule is important, although they may be oversimplifying, its worth listening to them. They are afterall at the coalface of dealing with 1,000s of these claims across the country.

**Comment by geeksareforlife** [comment]
This is not relevant to rules consultation, is covered in members's guide
