### ISSUE TITLE
Could we change one letter ... ?

### ISSUE THREAD

**Issue by forthespacemen** [NottingHack/rules#31]
Looked at all the rules now and FWIW, think they're all excellent - specially Be Excellent To One Another. But there's the issue for me, embedded in link [1] which ==> SafeSpaces policy.
Could we call it SafeSpace policy ? This is Hackspace, not Hackspaces, albeit there's going to be 2.5 accessed by a flight of stairs. 

SafeSpaces , plural as here, connotes all sorts of very recent political things, like no-platforming people in institutions of Higher Education (until not so long ago spaces for open and free debate and discussion) ; areas on campuses reserved for people of a certain race ; and erasing / denying history by tearing down sculptures and etc., etc. 

I don't know if the phrase "SafeSpaces Policy" was intended to evoke this overtly political aspect, to be embedded in our rules ?

(Can't fault the actual policy)

**Comment by msemtd** [comment]
The policy stands by its content and not its name - I'm pretty sure that "SafeSpace" has all the same connotations to those that cry "PC gone mad!" in response to any perceived opposition to their (offensive) views. I still like the name "Don't Be a Dick policy"

**Comment by geeksareforlife** [comment]
I'm happy to change to either.  It wasn't chosen because of the recent political university issues, in fact those policies were named after the same tech-conference policies we drew on to create this.

That said, we don't suffer from the same issues as universities - they are public spaces so have a need to allow free speech.  We are a private space and don't have any such requirement.

We obviously work very hard to ensure that there are freedoms in the space, but we draw the line at true "free speech" - as per this policy, there are restrictions on what you can say when at the space.

As the consultation ends today, and this policy is not technically a "rule" - it has been added as an appendix to keep it all in one place and allow easy updating, feel free to continue this discussion on the google group if you would like to.

**Comment by jamesfowkes** [comment]
I think Safe Spaces (plural) makes sense as we don't just do things in the physical building. We have an extensive online presence and do external events, both of which the policy should also apply to.

**Comment by forthespacemen** [comment]
Yup; I take all those very fair points. I guess I'm over-sensitive about the phrase "safe spaces" in contemporary political ... 'discourse'
